# Generated by Django 6.0.6 on 2026-06-09 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['-create_date'], 'verbose_name': 'record', 'verbose_name_plural': 'records'},
        ),
    ]
