# Generated by Django 6.0.6 on 2026-06-09 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_record_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['-id'], 'verbose_name': 'record', 'verbose_name_plural': 'records'},
        ),
    ]
